/**
 * Facts about each city from Wikidata (CC0) and Wikipedia (CC BY-SA), generated by scripts/enrich-cities.ts
 * into cityFacts.json. Link `summary.source` wherever the Wikipedia text is shown.
 */
import data from './cityFacts.json';

export interface CityFacts {
  wikidata: { town: string; municipality: string };
  /** Short Wikidata description, e.g. "Kryeqyteti i Shqipërisë". */
  description?: { text: string; lang: string };
  /** First sentences of the Wikipedia article (Albanian preferred). */
  summary?: { text: string; lang: string; source: string };
  population?: { value: number; year?: number };
  areaKm2?: number;
  elevationM?: number;
  website?: string;
}

const facts = data.cities as Record<string, CityFacts>;
export const getFacts = (slug: string): CityFacts | undefined => facts[slug];

const number = new Intl.NumberFormat('sq-AL');
export const wikidataUrl = (facts: CityFacts) => `https://www.wikidata.org/wiki/${facts.wikidata.town}`;

/** The figures worth showing, already formatted in Albanian: "557 mijë" inhabitants, "1.088 km²", "110 m". */
export function factLines(facts: CityFacts): { label: string; value: string; note?: string }[] {
  const lines: { label: string; value: string; note?: string }[] = [];
  const people = facts.population;
  if (people) lines.push({ label: 'Banorë', value: people.value >= 100_000 ? `${Math.round(people.value / 1000)} mijë` : number.format(people.value), note: people.year ? `Të dhëna të vitit ${people.year}` : undefined });
  if (facts.areaKm2) lines.push({ label: 'Sipërfaqja', value: `${number.format(facts.areaKm2)} km²`, note: 'Bashkia ose komuna' });
  if (facts.elevationM) lines.push({ label: 'Lartësia', value: `${number.format(facts.elevationM)} m` });
  return lines;
}
